$<PLATFORMIO_INI>
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; This file was generated by GUIsliceBuilder
; DO NOT edit directly. It will be deleted and
; recreated during your next Code Generation.
;
; If necessary, you may edit 
; GUIsliceBuilder/templates/platformio.t instead.
;
; PlatformIO Project Configuration file for GUIslice
; - https://github.com/ImpulseAdventure/GUIslice
;
; - This file will be used to select the MCU, Display
;   and Touch drivers to use with GUIslice
;
; * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

; =========================================================
; Section 1: PlatformIO GENERAL SETTINGS
; =========================================================

[platformio]

; Extra config:
; - PlatformIO config to build from project root
;lib_dir = .

; Default environments to load
default_envs =
$<DEFAULT_ENV>

[env]
; GUIslice compilation more straightforward in "deep" LDF mode
lib_ldf_mode = deep
; To enable inspect/cppcheck w/o LTO1 error, disable LTO
build_unflags =
;	-flto

[common]
; Define any additional compilation flags here
build_flags =
;	-Wall
;	-Wextra
;	-Wunused-variable

; ---------------------------------------------------------------------
; PlatformIO GUIslice Environments
;
; - The GUIslice configurations have been pulled from the
;   associated GUIslice /configs/ files.
; - If you have an existing GUIslice config file,
;   it is relatively easy to add your own environment
;   Read GUIsliceBuilder UserGuide 'Chapter 6 PlatformIO Configuration'.
; ----------------------------------------------------------------------

$<GUIslice_ENV>

; ...
<STOP>
